version: "3.2"
services:
  nextjs:
    image: abc-frontend:latest
    platform: linux/amd64
    build:
      context: ./
    ports:
      - "3000:3000"
    restart: always
    networks:
      - abcnetwork
    volumes:
      - abc-website-node_modules:/app/node_modules
    environment:
      NEXT_PUBLIC_MAILCHIMP_URL: ${NEXT_PUBLIC_MAILCHIMP_URL}
      NEXT_PUBLIC_STRAPI_API_URL: ${NEXT_PUBLIC_STRAPI_API_URL}
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    restart: always
    networks:
      - abcnetwork

networks:
  abcnetwork:
    driver: bridge

volumes:
  abc-website-node_modules:
