version: "3.2"
services:
  nextjs:
    image: abc-frontend-prod:latest
    platform: linux/amd64
    build:
      context: ../../
      dockerfile: docker/production/Dockerfile
    ports:
      - "3000:3000"
    restart: always
    networks:
      - abcnetwork-prod
    volumes:
      - abc-website-node_modules-prod:/app/node_modules

  nginx:
    build: ../../nginx
    ports:
      - "80:80"
    restart: always
    networks:
      - abcnetwork-prod

networks:
  abcnetwork-prod:
    driver: bridge

volumes:
  abc-website-node_modules-prod:
