version: "3.2"
services:
  nextjs:
    image: abc-frontend-stage:latest
    platform: linux/amd64
    build:
      context: ../../
      dockerfile: docker/staging/Dockerfile
    ports:
      - "3000:3000"
    restart: always
    networks:
      - abcnetwork-stage
    volumes:
      - abc-website-node_modules-stage:/app/node_modules

  nginx:
    build: ../../nginx
    ports:
      - "80:80"
    restart: always
    networks:
      - abcnetwork-stage

networks:
  abcnetwork-stage:
    driver: bridge

volumes:
  abc-website-node_modules-stage:
